---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.0
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 4.0.0"
  - PUPPET_GEM_VERSION="~> 4.1.0"
  - PUPPET_GEM_VERSION="~> 4.2.0"
  - PUPPET_GEM_VERSION="~> 4.3.0"
  - PUPPET_GEM_VERSION="~> 4.4.0"
  - PUPPET_GEM_VERSION="~> 4.5.0"
  - PUPPET_GIT_URL="https://github.com/puppetlabs/puppet.git"
matrix:
  fast_finish: true
  exclude:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.0.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.1.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.3.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.2.0"
    - rvm: 1.8.7
      env: PUPPET_GIT_URL="https://github.com/puppetlabs/puppet.git"
  allow_failures:
    - env: PUPPET_GIT_URL="https://github.com/puppetlabs/puppet.git"
